name: Run in-toto tests and linter

on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        run: echo build
